apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: mariadb
  name: mariadb
spec:
  containers:
  - capabilities: {}
    env:
    - name: DBUSER
      value: $db_user
    - name: DBPASS
      value: $db_pass
    - name: DBNAME
      value: $db_name
    image: $image
    name: mariadb
    ports:
    - containerPort: 3306
      protocol: TCP
    resources:
      limits:
        cpu: 100m
