apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: wpfrontend
  name: wordpress
spec:
  containers:
  - env:
    - name: DB_ENV_DBUSER
      value: $db_user 
    - name: DB_ENV_DBPASS
      value: $db_pass
    - name: DB_ENV_DBNAME
      value: $db_name
    image: $image
    name: wordpress
    ports:
    - containerPort: 80
      protocol: TCP
