apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: wpfrontend
  name: wpfrontend
spec:
  createExternalLoadBalancer: true
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: wpfrontend
