apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: wpfrontend
  name: wordpress
spec:
  containers:
  - env:
    - name: DB_ENV_DBUSER
      value: user
    - name: DB_ENV_DBPASS
      value: mypassword
    - name: DB_ENV_DBNAME
      value: mydb
    image: summit-rhel-dev:5000/wordpress
    name: wordpress
    ports:
    - containerPort: 80
      protocol: TCP
