apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    name: wpfrontend
  name: wordpress
spec:
  containers:
  - env:
    image: dev.example.com:5000/wordpress
    name: wordpress
    ports:
    - containerPort: 80
      protocol: TCP
